### ISSUE TITLE
it's have gap when tooltip number over 10 or 100.

### ISSUE THREAD

**Issue by ausir0726** [biigpongsatorn/vue-slide-bar#10]
if the tooltip number over 10 or 100, it's will have a gap between number and line.

![image](https://user-images.githubusercontent.com/7247064/45082394-cf093f80-b12b-11e8-90e5-3d4d6395bfd1.png)

**Comment by heihachi88** [comment]
Confirm this, by the way, have you managed to center these labels:

![image](https://user-images.githubusercontent.com/5739191/45084883-27870f80-b121-11e8-97d5-fe0657179dc2.png)

As you can see, edges goes beyond the progress bar... I can't figure out.

**Comment by ausir0726** [comment]
I don't have use label this time.

**Comment by biigpongsatorn** [comment]
@ausir0726 I solved this issue. You can update to version `1.1.3` and try again 😉
