### ISSUE TITLE
Issue with labels beyond the slidebar

### ISSUE THREAD

**Issue by heihachi88** [biigpongsatorn/vue-slide-bar#11]
![image](https://user-images.githubusercontent.com/5739191/45084883-27870f80-b121-11e8-97d5-fe0657179dc2.png)

As you can see, edges goes beyond the progress bar... How to set labels to not leave progress bar width:

![image](https://user-images.githubusercontent.com/5739191/45137446-8359a300-b1ca-11e8-86d2-3a1161f0e36a.png)

How to accomplish this?

If i play with translate - i can achieve that, but slider-dot won't be centered correctly then, there's hardcoded values in a script itself.

**Comment by biigpongsatorn** [comment]
@heihachi88 
This component will fix label position to middle of pointer, now you can't custom this by programatic.
But you can play with translate like this. 

```html
<vue-slide-bar
  id="slide-bar-time-rang"
  v-model="slider.value"
  :data="slider.data"
  :range="slider.range"
  :processStyle="{ backgroundColor: '#d8d8d8' }"
  @callbackRange="callbackRange">
  <template slot="tooltip" slot-scope="tooltip">
    <img src="static/images/rectangle-slider.svg">
  </template>
</vue-slide-bar>

<style>
#slide-bar-time-rang .vue-slide-bar-separate:first-child span {
  transform: translate(0, 0) !important;
}
#slide-bar-time-rang .vue-slide-bar-separate:last-child span {
  transform: translate(-100%, 0) !important;
}
</style>
```

**Comment by biigpongsatorn** [comment]
![image](https://user-images.githubusercontent.com/10693658/45139092-dcc8ce80-b1d8-11e8-9b02-fe3f84b672a7.png)

**Comment by heihachi88** [comment]
Try to move that dot to 15 mins position, how it would look?

**Comment by biigpongsatorn** [comment]
@heihachi88 You want to move this dot right ? (`'`)
![image](https://user-images.githubusercontent.com/10693658/45139285-76907b80-b1d9-11e8-94e5-e7ee1c74802c.png)

or this ?
![image](https://user-images.githubusercontent.com/10693658/45139304-7ee8b680-b1d9-11e8-8a0f-14256d7ef7b0.png)

**Comment by biigpongsatorn** [comment]
![image](https://user-images.githubusercontent.com/10693658/45139934-92951c80-b1db-11e8-928e-c49fc988deaf.png)

**Comment by heihachi88** [comment]
That's the problem, it should be centered like this:

![image](https://user-images.githubusercontent.com/5739191/45142329-1817cd00-b1da-11e8-95f1-c625c17c25c5.png)

Same on the right side.

**Comment by biigpongsatorn** [comment]
@heihachi88  Sorry, now you can't  align pointer like this.

**Comment by heihachi88** [comment]
Damn :( everything is ok, except this pointer, any workarounds maybe?

**Comment by heihachi88** [comment]
Thank, would try it out. Also i cloned your repo and couldn’t understand
the math to move the dot, how do you calculate on how much pixels to move
on press? Does it depends on the size of dot slider?

**Comment by heihachi88** [comment]
Your fiddle is empty, btw. Also if i have different color, lets say "blue", when you move to the right.

**Comment by biigpongsatorn** [comment]
@heihachi88  You can set `background-color` of class `.fake-line-right` when your `v-model` = `2hrs`.
