### ISSUE TITLE
Toggle for tooltip styles (for dot style "tooltip")

### ISSUE THREAD

**Issue by andreasvirkus** [biigpongsatorn/vue-slide-bar#12]
Hi, love the small component that you've made! Although this is not a blocker for us, here's a small suggestion/favor:

We need to achieve the following design:
![screen shot 2018-09-10 at 16 33 22](https://user-images.githubusercontent.com/9140811/45300532-44538680-b517-11e8-818a-09a4ad09da9b.png)

I can currently achieve it via
```
<slide-bar v-model="rating"
          :lineHeight="4"
          :processStyle="{ backgroundColor: '#475DE5' }"
          :tooltipStyles="{
            position: 'absolute',
            background: 'linear-gradient(180deg, #FFFFFF 0%, #F9FAFB 100%)',
            border: '1px solid #B9C3D4',
            borderRadius: '50%',
            width: '1.5rem',
            height: '1.5rem',
            transform: 'translateY(1rem)'
          }"
          :data="[0, 0.2, 0.4, 0.6, 0.8, 1, 1.2, 1.4, 1.6, 1.8, 2]" />
```

But the `padding-top: 40px !important` and the pseudo element (arrow) are a hard one to bite through in a clean way (atm I'm adding a class twice to fight specificity and can't remove them via props). https://github.com/biigpongsatorn/vue-slide-bar/blob/6f13162c176a66a23e119646d2cd82c4af8b91ca/src/components/VueSlideBar.vue#L368

Could you create a prop that removes the top padding?
Maybe that prop could also apply some base styles for a rounded "tooltip"? For example:
```
:tooltipStyles="{
  position: 'absolute',
  borderRadius: '50%',
  width: '1.5rem',
  height: '1.5rem',
  transform: 'translateY(1rem)'
}"

.vue-slide-bar-component {
  padding-top: 0;
}
.vue-slide-bar-tooltip::before {
  content: none;
}
```

**Comment by biigpongsatorn** [comment]
@andreasvirkus Thank you for your suggestion 🙂.

I added new prop name `paddingless` to new version `1.1.5`,
You can remove padding and min-height of container with set `paddingless = true`
