### ISSUE TITLE
Is JSX supported?

### ISSUE THREAD

**Issue by betweenbrain** [biigpongsatorn/vue-slide-bar#21]
Hello,

This looks like a great component, but I was wondering if there is any way to use it with JSX & `render()` as opposed to templates and `v-model`.

Thanks!

**Comment by biigpongsatorn** [comment]
I'm not sure about that but I think it can, This is just a simple component. If another component can use with JSX this component will be.

It's will amazing if you can try using this component with JSX and tell me the result.

Thanks.

**Comment by betweenbrain** [comment]
@biigpongsatorn thanks for the response. The issue I am trying to solve is that your component seems to rely on `v-model`, which the _babel-plugin-transform-vue-jsx_ does not support, see https://github.com/vuejs/babel-plugin-transform-vue-jsx/issues/36.

However, I did come up with a solution that works for my case. I added a _ref_ attribute to the `VueSlideBar` element, and watch that ref's _slider.currentValue_ with:

**Comment by biigpongsatorn** [comment]
@betweenbrain Look good, But actually, you can use an event `@input` to solve your problem.

I think it better than use `$watch` function.

example:
https://github.com/vuejs/babel-plugin-transform-vue-jsx/issues/36#issuecomment-263406217

Good luck 🙂

**Comment by betweenbrain** [comment]
Hello @biigpongsatorn. Thanks, that is much better!
