### ISSUE TITLE
NEED ! Demo page

### ISSUE THREAD

**Issue by biigpongsatorn** [biigpongsatorn/vue-slide-bar#3]

**Comment by frncsdrk** [comment]
What is the goal of the demo page? Should it just show different interactive demos or have code examples / documentation too?

**Comment by biigpongsatorn** [comment]
@frncsdrk  Just show different interactive demos 😊

**Comment by frncsdrk** [comment]
OK, so how about creating the page in a separate repository to keep this one clean?

**Comment by biigpongsatorn** [comment]
@frncsdrk  Sure. I think it should separate repository. 🙂

**Comment by biigpongsatorn** [comment]
@frncsdrk  You can make a demo page and add your site to README of this repository if you want to be contributor. 🙂

**Comment by biigpongsatorn** [comment]
Cool. Can i fork your repository and deploy to [Netlify](https://www.netlify.com/) ?

**Comment by biigpongsatorn** [comment]
Or can you add me to collaborator of https://github.com/frncsdrk/vue-slide-bar-demo-page repository ? @frncsdrk

**Comment by biigpongsatorn** [comment]
How to run your project in local ? Can you add script to package.json ?

**Comment by biigpongsatorn** [comment]
I publish your demo live on https://vue-slide-bar-demo-page.netlify.com/

Now i use my fork repository to deploy site. but if you want to use [main repository](https://github.com/frncsdrk/vue-slide-bar-demo-page) you can add me to collaborator.

Thank you very much for your support 🙂
