### ISSUE TITLE
How can i use this package with typescript?

### ISSUE THREAD

**Issue by liudavid0107** [biigpongsatorn/vue-slide-bar#36]
@biigpongsatorn 
I want to use this package in a typescript project.
But I got an error when using this package with typescript.
Are there any `types` package for `vue-slide-bar`?
Thanks in advance.

**Comment by biigpongsatorn** [comment]
This package is not build with typescript but I think it's should compatible with Typescript.
Can you show your error?

**Comment by liudavid0107** [comment]
simple error. @biigpongsatorn 

![1](https://user-images.githubusercontent.com/65745739/87876765-e5150600-ca0c-11ea-8fd0-24cce8a03760.PNG)

**Comment by biigpongsatorn** [comment]
https://link.medium.com/hRfmArlyf8

This article clarify about this issue.
