### ISSUE TITLE
Configurable label style

### ISSUE THREAD

**Issue by frncsdrk** [biigpongsatorn/vue-slide-bar#4]
It would be great if the styling of the labels would be configurable e.g.
- color
- font-size
- ...

**Comment by biigpongsatorn** [comment]
Thank you for your suggestion. Your issue has been resolved. #5 

Please update vue-slide-bar to version vue-slide-bar@1.0.7

You can custom label style with label-styles.

Example 

```
:labelStyles="{ color: '#4a4a4a', backgroundColor: '#4a4a4a' }"
```

**Comment by frncsdrk** [comment]
That's great! Thank you!
