### ISSUE TITLE
Outdated package contents published

### ISSUE THREAD

**Issue by frncsdrk** [biigpongsatorn/vue-slide-bar#7]
It seems like the currently published version of the package still contains the old code.  
I had a look at your publish command (`rm -rf ./dist && bili src/components/VueSlideBar.vue`). Could you tell me what `bili` is?

**Comment by biigpongsatorn** [comment]
https://github.com/egoist/bili

**Comment by biigpongsatorn** [comment]
Oh sorry i forgot build before publish lol.

**Comment by frncsdrk** [comment]
It works! And thank you! @biigpongsatorn
