### ISSUE TITLE
Question : value as Array

### ISSUE THREAD

**Issue by ChristianRiedl** [biigpongsatorn/vue-slide-bar#8]
I do not understand why value can be an array of values. Please be so kind and tell me what is the intention.

**Comment by biigpongsatorn** [comment]
@ChristianRiedl 
Sorry document is wrong.

I updated document. 
`value` can be `Number` or `String` depend on `data`.
If you have `data`, `value` will be the same type as `data`.
If `data` is string `value` type will be `String`

```
data: ['a','b','c','d','e','f','g','h'],
value: 'c' // default value.
```

If you not have `data` `value` type will be only `Number`.
